//
// auto-generated by op2.m on 19-Oct-2012 16:21:04
//

// header

#include "op_lib_cpp.h"

#include "op_cuda_rt_support.h"
#include "op_cuda_reduction.h"
// global constants

#ifndef MAX_CONST_SIZE
#define MAX_CONST_SIZE 128
#endif

__constant__ double gam;
__constant__ double gm1;
__constant__ double gm1i;
__constant__ double m2;
__constant__ double wtg1[2];
__constant__ double xi1[2];
__constant__ double Ng1[4];
__constant__ double Ng1_xi[4];
__constant__ double wtg2[4];
__constant__ double Ng2[16];
__constant__ double Ng2_xi[32];
__constant__ double minf;
__constant__ double freq;
__constant__ double kappa;
__constant__ double nmode;
__constant__ double mfan;
__constant__ int op2_stride;

#define OP2_STRIDE(arr, idx) arr[op2_stride*(idx)]

void op_decl_const_gam(int dim, char const *type, double *dat){
  cutilSafeCall(cudaMemcpyToSymbol(gam , dat, dim*sizeof(double)));
}

void op_decl_const_gm1(int dim, char const *type, double *dat){
  cutilSafeCall(cudaMemcpyToSymbol(gm1 , dat, dim*sizeof(double)));
}

void op_decl_const_gm1i(int dim, char const *type, double *dat){
  cutilSafeCall(cudaMemcpyToSymbol(gm1i , dat, dim*sizeof(double)));
}

void op_decl_const_m2(int dim, char const *type, double *dat){
  cutilSafeCall(cudaMemcpyToSymbol(m2 , dat, dim*sizeof(double)));
}

void op_decl_const_wtg1(int dim, char const *type, double *dat){
  cutilSafeCall(cudaMemcpyToSymbol(wtg1 , dat, dim*sizeof(double)));
}

void op_decl_const_xi1(int dim, char const *type, double *dat){
  cutilSafeCall(cudaMemcpyToSymbol(xi1 , dat, dim*sizeof(double)));
}

void op_decl_const_Ng1(int dim, char const *type, double *dat){
  cutilSafeCall(cudaMemcpyToSymbol(Ng1 , dat, dim*sizeof(double)));
}

void op_decl_const_Ng1_xi(int dim, char const *type, double *dat){
  cutilSafeCall(cudaMemcpyToSymbol(Ng1_xi , dat, dim*sizeof(double)));
}

void op_decl_const_wtg2(int dim, char const *type, double *dat){
  cutilSafeCall(cudaMemcpyToSymbol(wtg2 , dat, dim*sizeof(double)));
}

void op_decl_const_Ng2(int dim, char const *type, double *dat){
  cutilSafeCall(cudaMemcpyToSymbol(Ng2 , dat, dim*sizeof(double)));
}

void op_decl_const_Ng2_xi(int dim, char const *type, double *dat){
  cutilSafeCall(cudaMemcpyToSymbol(Ng2_xi , dat, dim*sizeof(double)));
}

void op_decl_const_minf(int dim, char const *type, double *dat){
  cutilSafeCall(cudaMemcpyToSymbol(minf , dat, dim*sizeof(double)));
}

void op_decl_const_freq(int dim, char const *type, double *dat){
  cutilSafeCall(cudaMemcpyToSymbol(freq , dat, dim*sizeof(double)));
}

void op_decl_const_kappa(int dim, char const *type, double *dat){
  cutilSafeCall(cudaMemcpyToSymbol(kappa , dat, dim*sizeof(double)));
}

void op_decl_const_nmode(int dim, char const *type, double *dat){
  cutilSafeCall(cudaMemcpyToSymbol(nmode , dat, dim*sizeof(double)));
}

void op_decl_const_mfan(int dim, char const *type, double *dat){
  cutilSafeCall(cudaMemcpyToSymbol(mfan , dat, dim*sizeof(double)));
}

// user kernel files

#include "res_calc_kernel.cu"
#include "dirichlet_kernel.cu"
#include "init_cg_kernel.cu"
#include "spMV_kernel.cu"
#include "dotPV_kernel.cu"
#include "updateUR_kernel.cu"
#include "dotR_kernel.cu"
#include "updateP_kernel.cu"
#include "update_kernel.cu"
