//
// auto-generated by op2.py on 2015-06-05 14:38
//

// header
#include "op_lib_cpp.h"
#ifdef VECTORIZE
#define SIMD_VEC 4
#define ALIGNED_double __attribute__((aligned(128)))
#define ALIGNED_float __attribute__((aligned(64)))
#define ALIGNED_int __attribute__((aligned(64)))
#else
#define ALIGNED_double
#define ALIGNED_float
#define ALIGNED_int
#endif

// global constants
extern double gam;
extern double gm1;
extern double cfl;
extern double eps;
extern double mach;
extern double alpha;
extern double qinf[4];
// user kernel files
#include "save_soln_veckernel.cpp"
#include "adt_calc_veckernel.cpp"
#include "res_calc_veckernel.cpp"
#include "bres_calc_veckernel.cpp"
#include "update_veckernel.cpp"
