//
// auto-generated by op2.py
//

// header
#include "op_lib_cpp.h"

// user kernel files
#include "save_soln_omp4kernel.cpp"
#include "adt_calc_omp4kernel.cpp"
#include "res_calc_omp4kernel.cpp"
#include "bres_calc_omp4kernel.cpp"
#include "update_omp4kernel.cpp"
