//
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
// auto-generated by op2.py on 2015-07-08 13:58
=======
// auto-generated by op2.py on 2015-06-01 13:42
>>>>>>> 6464d9e... Reverting genseq to non vectorised version
=======
// auto-generated by op2.py on 2015-06-05 14:38
>>>>>>> 24074af... Fixing minor error in vectorized C version of Airfoil
=======
// auto-generated by op2.py on 2015-06-09 13:59
>>>>>>> eb884cb... exploring further optimisations
//

// header
#include "op_lib_cpp.h"

// global constants
extern double gam;
extern double gm1;
extern double cfl;
extern double eps;
extern double mach;
extern double alpha;
extern double qinf[4];
// user kernel files
#include "save_soln_seqkernel.cpp"
#include "adt_calc_seqkernel.cpp"
#include "res_calc_seqkernel.cpp"
#include "bres_calc_seqkernel.cpp"
#include "update_seqkernel.cpp"
