!
! auto-generated by op2.py on 2013-01-25 10:09
!

program AIRFOIL
  use OP2_FORTRAN_DECLARATIONS
  use SAVE_SOLN_MODULE
  use ADT_CALC_MODULE
  use RES_CALC_MODULE
  use BRES_CALC_MODULE
  use UPDATE_MODULE
  use OP2_Fortran_RT_Support
  use OP2_CONSTANTS
  use AIRFOIL_SEQ
  use, intrinsic :: ISO_C_BINDING

  implicit none

  intrinsic :: sqrt, real

  integer(4) :: iter, k, i

  integer(4), parameter :: maxnode = 9900
  integer(4), parameter :: maxcell = (9702+1)
  integer(4), parameter :: maxedge = 19502

  integer(4), parameter :: iterationNumber = 1000

  integer(4) :: nnode, ncell, nbedge, nedge, niter, qdim
  real(8) :: ncellr

  ! profiling
  real(kind=c_double) :: startTime = 0
  real(kind=c_double) :: endTime = 0

  ! integer references (valid inside the OP2 library) for op_set
  type(op_set) :: nodes, edges, bedges, cells

  ! integer references (valid inside the OP2 library) for pointers between data sets
  type(op_map) :: pedge, pecell, pcell, pbedge, pbecell

  ! integer reference (valid inside the OP2 library) for op_data
  type(op_dat) :: p_bound, p_x, p_q, p_qold, p_adt, p_res

  ! arrays used in data
  integer(4), dimension(:), allocatable, target :: ecell, bound, edge, bedge, becell, cell
  real(8), dimension(:), allocatable, target :: x, q, qold, adt, res
  real(8) :: rms

  character(kind=c_char,len=10) :: savesolnName = C_CHAR_'save_soln'//C_NULL_CHAR
  character(kind=c_char, len=9) :: adtcalcName  = C_CHAR_'adt_calc' // C_NULL_CHAR
  character(kind=c_char, len=9) :: rescalcName  = C_CHAR_'res_calc' // C_NULL_CHAR
  character(kind=c_char,len=10) :: brescalcName = C_CHAR_'bres_calc' // C_NULL_CHAR
  character(kind=c_char, len=7) :: updateName   = C_CHAR_'update' // C_NULL_CHAR

  character(kind=c_char,len=6) :: nodesName  = C_CHAR_'nodes'//C_NULL_CHAR
  character(kind=c_char,len=6) :: edgesName  = C_CHAR_'edges'//C_NULL_CHAR
  character(kind=c_char,len=7) :: bedgesName = C_CHAR_'bedges'//C_NULL_CHAR
  character(kind=c_char,len=6) :: cellsName  = C_CHAR_'cells'//C_NULL_CHAR

  character(kind=c_char,len=6) :: pedgeName   = C_CHAR_'pedge'//C_NULL_CHAR
  character(kind=c_char,len=7) :: pecellName  = C_CHAR_'pecell'//C_NULL_CHAR
  character(kind=c_char,len=6) :: pcellName   = C_CHAR_'pcell'//C_NULL_CHAR
  character(kind=c_char,len=7) :: pbedgeName  = C_CHAR_'pbedge'//C_NULL_CHAR
  character(kind=c_char,len=8) :: pbecellName = C_CHAR_'pbecell'//C_NULL_CHAR

  character(kind=c_char,len=6) :: boundName = C_CHAR_'bound'//C_NULL_CHAR
  character(kind=c_char,len=2) :: xName     = C_CHAR_'x'//C_NULL_CHAR
  character(kind=c_char,len=2) :: qName     = C_CHAR_'q'//C_NULL_CHAR
  character(kind=c_char,len=5) :: qoldName  = C_CHAR_'qold'//C_NULL_CHAR
  character(kind=c_char,len=4) :: adtName   = C_CHAR_'adt'//C_NULL_CHAR
  character(kind=c_char,len=4) :: resName   = C_CHAR_'res'//C_NULL_CHAR

  character(kind=c_char,len=4) :: gamName   = C_CHAR_'gam'//C_NULL_CHAR
  character(kind=c_char,len=4) :: gm1Name   = C_CHAR_'gm1'//C_NULL_CHAR
  character(kind=c_char,len=4) :: cflName   = C_CHAR_'cfl'//C_NULL_CHAR
  character(kind=c_char,len=4) :: epsName   = C_CHAR_'eps'//C_NULL_CHAR
  character(kind=c_char,len=5) :: machName   = C_CHAR_'mach'//C_NULL_CHAR
  character(kind=c_char,len=6) :: alphaName   = C_CHAR_'alpha'//C_NULL_CHAR
  character(kind=c_char,len=5) :: qinfName   = C_CHAR_'qinf'//C_NULL_CHAR

  integer(4) :: debugiter, retDebug
  real(8) :: datad

  character(kind=c_char,len=12) :: FileName = C_CHAR_'new_grid.h5'//C_NULL_CHAR

  ! local variables for constant initialization
  real(8) :: p, r, u, e

  print *, "Initialising constants"
  gam = 1.4
  gm1 = gam - 1.0
  cfl = 0.9
  eps = 0.05

  mach  = 0.4
  alpha = 3.0 * atan(1.0) / 45.0
  p     = 1.0
  r     = 1.0
  u     = sqrt ( gam * p / r ) * mach
  e     = p / ( r * gm1 ) + 0.5 * u * u

  qinf(1) = r
  qinf(2) = r * u
  qinf(3) = 0.0
  qinf(4) = r * e

  ! OP initialisation
  print *, "Initialising OP2"
  call op_init (0)

  ! declare sets, pointers, datasets and global constants (for now, no new partition info)
  print *, "Declaring OP2 sets"
  call op_decl_set_hdf5 ( nnode, nodes, FileName, "nodes" )
  call op_decl_set_hdf5 ( nedge, edges, FileName, "edges" )
  call op_decl_set_hdf5 ( nbedge, bedges, FileName, "bedges" )
  call op_decl_set_hdf5 ( ncell, cells, FileName, "cells" )

  print *, "Declaring OP2 maps"
  call op_decl_map_hdf5 ( edges, nodes, 2, pedge, FileName, "pedge" )
  call op_decl_map_hdf5 ( edges, cells, 2, pecell, FileName, "pecell" )
  call op_decl_map_hdf5 ( bedges, nodes, 2, pbedge, FileName, "pbedge" )
  call op_decl_map_hdf5 ( bedges, cells, 1, pbecell, FileName, "pbecell" )
  call op_decl_map_hdf5 ( cells, nodes, 4, pcell, FileName, "pcell" )

  print *, "Declaring OP2 data"
  call op_decl_dat_hdf5 ( bedges, 1, p_bound, "int", FileName, "p_bound" )
  call op_decl_dat_hdf5 ( nodes, 2, p_x, "double", FileName, "p_x" )
  call op_decl_dat_hdf5 ( cells, 4, p_q, "double", FileName, "p_q" )
  call op_decl_dat_hdf5 ( cells, 4, p_qold, "double", FileName, "p_qold" )
  call op_decl_dat_hdf5 ( cells, 1, p_adt, "double", FileName, "p_adt" )
  call op_decl_dat_hdf5 ( cells, 4, p_res, "double", FileName, "p_res" )

  print *, "Declaring OP2 constants"
  call op_decl_const (gam, 1, gamName)
  call op_decl_const (gm1, 1, gm1Name)
  call op_decl_const (cfl, 1, cflName)
  call op_decl_const (eps, 1, epsName)
  call op_decl_const (mach, 1, machName)
  call op_decl_const (alpha, 1, alphaName)
  call op_decl_const (qinf, 4, qinfName)

  call op_partition ("PARMETIS", "KWAY", edges, pecell, p_x)
  ncellr = real(op_get_size(cells))
  print *, "ncellr", ncellr

  ! start timer
  call op_timers ( startTime )

  ! main time-marching loop

  do niter = 1, iterationNumber

     call save_soln_host("save_soln",cells, &
                      & op_arg_dat(p_q,-1,OP_ID,OP_READ), &
                      & op_arg_dat(p_qold,-1,OP_ID,OP_WRITE))

    ! predictor/corrector update loop

    do k = 1, 2

      ! calculate area/timstep
      call adt_calc_host("adt_calc",cells, &
                       & op_arg_dat(p_x,1,pcell,OP_READ), &
                       & op_arg_dat(p_x,2,pcell,OP_READ), &
                       & op_arg_dat(p_x,3,pcell,OP_READ), &
                       & op_arg_dat(p_x,4,pcell,OP_READ), &
                       & op_arg_dat(p_q,-1,OP_ID,OP_READ), &
                       & op_arg_dat(p_adt,-1,OP_ID,OP_WRITE))

      ! calculate flux residual
      call res_calc_host("res_calc",edges, &
                       & op_arg_dat(p_x,1,pedge,OP_READ), &
                       & op_arg_dat(p_x,2,pedge,OP_READ), &
                       & op_arg_dat(p_q,1,pecell,OP_READ), &
                       & op_arg_dat(p_q,2,pecell,OP_READ), &
                       & op_arg_dat(p_adt,1,pecell,OP_READ), &
                       & op_arg_dat(p_adt,2,pecell,OP_READ), &
                       & op_arg_dat(p_res,1,pecell,OP_INC), &
                       & op_arg_dat(p_res,2,pecell,OP_INC))

      call bres_calc_host("bres_calc",bedges, &
                       & op_arg_dat(p_x,1,pbedge,OP_READ), &
                       & op_arg_dat(p_x,2,pbedge,OP_READ), &
                       & op_arg_dat(p_q,1,pbecell,OP_READ), &
                       & op_arg_dat(p_adt,1,pbecell,OP_READ), &
                       & op_arg_dat(p_res,1,pbecell,OP_INC), &
                       & op_arg_dat(p_bound,-1,OP_ID,OP_READ))

      ! update flow field

      rms = 0.0

      call update_host("update",cells, &
                       & op_arg_dat(p_qold,-1,OP_ID,OP_READ), &
                       & op_arg_dat(p_q,-1,OP_ID,OP_WRITE), &
                       & op_arg_dat(p_res,-1,OP_ID,OP_RW), &
                       & op_arg_dat(p_adt,-1,OP_ID,OP_READ), &
                       & op_arg_gbl(rms,OP_INC))


    end do ! internal loop

    !ncellr = real ( ncell )
    rms = sqrt ( rms / ncellr )

    if (mod(niter,100) .eq. 0)  write (*,*), niter,"  ",rms

  end do ! external loop

  call op_timers ( endTime )
  write (*,*), 'Max total runtime =', endTime - startTime,'seconds'
  call op_exit (  )

end program AIRFOIL
