//
// auto-generated by op2.m on 09-May-2012 16:29:07
//

// header

#include "op_lib_cpp.h"

// global constants

extern float alpha;

// user kernel files

#include "res_kernel.cpp"
#include "update_kernel.cpp"
