//
// auto-generated by op2.py
//

// global constants
extern long double gam;
extern long double gm1;
extern long double cfl;
extern long double eps;
extern long double mach;
extern long double alpha;
extern long double qinf[4];

// header
#include "op_lib_cpp.h"

// user kernel files
#include "save_soln_seqkernel.cpp"
#include "adt_calc_seqkernel.cpp"
#include "res_calc_seqkernel.cpp"
#include "bres_calc_seqkernel.cpp"
#include "update_seqkernel.cpp"
