!
! auto-generated by op2.py
!

MODULE BRES_CALC_MODULE
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE OP2_FORTRAN_JIT
USE OP2_CONSTANTS
USE AIRFOIL_SEQ
USE ISO_C_BINDING

CONTAINS

SUBROUTINE bres_calc_host( userSubroutine, set, &
  & opArg1, &
  & opArg2, &
  & opArg3, &
  & opArg4, &
  & opArg5, &
  & opArg6 )

  IMPLICIT NONE
  character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
  type ( op_set ) , INTENT(IN) :: set

  type ( op_arg ) , INTENT(IN) :: opArg1
  type ( op_arg ) , INTENT(IN) :: opArg2
  type ( op_arg ) , INTENT(IN) :: opArg3
  type ( op_arg ) , INTENT(IN) :: opArg4
  type ( op_arg ) , INTENT(IN) :: opArg5
  type ( op_arg ) , INTENT(IN) :: opArg6


  ! Define interface of call-back routine.
  abstract interface
      subroutine called_proc (userSubroutine, set, &
    & opArg1, &
    & opArg2, &
    & opArg3, &
    & opArg4, &
    & opArg5, &
    & opArg6) bind(c)

      use, intrinsic :: iso_c_binding
      USE OP2_FORTRAN_DECLARATIONS
      USE OP2_FORTRAN_RT_SUPPORT
      USE OP2_CONSTANTS

      !character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
      character(kind=c_char), dimension(*), intent(in) :: userSubroutine
      type ( op_set ) , INTENT(IN) :: set

      type ( op_arg ) , INTENT(IN) :: opArg1
      type ( op_arg ) , INTENT(IN) :: opArg2
      type ( op_arg ) , INTENT(IN) :: opArg3
      type ( op_arg ) , INTENT(IN) :: opArg4
      type ( op_arg ) , INTENT(IN) :: opArg5
      type ( op_arg ) , INTENT(IN) :: opArg6

      end subroutine called_proc
  end interface
  ! End interface of call-back routine

  procedure(called_proc), bind(c), pointer :: proc_bres_calc

  if (.not. JIT_COMPILED) then
    call jit_compile()
  end if

  call c_f_procpointer( proc_addr_bres_calc, proc_bres_calc )
  ! call/execute dynamically loaded procedure with the parameters from bres_calc_host() signature
  call proc_bres_calc( userSubroutine, set, &
  & opArg1, &
  & opArg2, &
  & opArg3, &
  & opArg4, &
  & opArg5, &
  & opArg6 )

END SUBROUTINE
END MODULE