//
// auto-generated by op2.py
//

// header
#include "op_lib_cpp.h"

// global constants
double gam_ompkernel;
double gm1_ompkernel;
double cfl_ompkernel;
double eps_ompkernel;
double mach_ompkernel;
double alpha_ompkernel;
double qinf_ompkernel[4];
void op_decl_const_char(int dim, char const *type,
int size, char *dat, char const *name){
if(!strcmp(name, "gam")){
    memcpy(&gam_ompkernel, dat, dim*size);
  } else if(!strcmp(name, "gm1")){
    memcpy(&gm1_ompkernel, dat, dim*size);
  } else if(!strcmp(name, "cfl")){
    memcpy(&cfl_ompkernel, dat, dim*size);
  } else if(!strcmp(name, "eps")){
    memcpy(&eps_ompkernel, dat, dim*size);
  } else if(!strcmp(name, "mach")){
    memcpy(&mach_ompkernel, dat, dim*size);
  } else if(!strcmp(name, "alpha")){
    memcpy(&alpha_ompkernel, dat, dim*size);
  } else if(!strcmp(name, "qinf")){
    memcpy(qinf_ompkernel, dat, dim*size);
  }
}
// user kernel files
#include "save_soln_ompkernel.cpp"
#include "adt_calc_ompkernel.cpp"
#include "res_calc_ompkernel.cpp"
#include "bres_calc_ompkernel.cpp"
#include "update_ompkernel.cpp"
