//
// auto-generated by op2.py
//

__constant__ int direct_update_stride_OP2CONSTANT;
int direct_update_stride_OP2HOST=-1;
//user function
__device__ void update_gpu( const double *qold, double *q, double *res,
                   const double *adt, double *rms) {
  double del, adti, rmsl;

  rmsl = 0.0f;
  adti = 1.0f / (*adt);

  for (int n = 0; n < 4; n++) {
    del = adti * res[(n)*direct_update_stride_OP2CONSTANT];
    q[(n)*direct_update_stride_OP2CONSTANT] = qold[(n)*direct_update_stride_OP2CONSTANT] - del;
    res[(n)*direct_update_stride_OP2CONSTANT] = 0.0f;
    rmsl += del * del;
  }
  *rms += rmsl;

}

// CUDA kernel function
__global__ void op_cuda_update(
  const double *__restrict arg0,
  double *arg1,
  double *arg2,
  const double *__restrict arg3,
  double *arg4,
  int   set_size ) {


  //process set elements
  for ( int n=threadIdx.x+blockIdx.x*blockDim.x; n<set_size; n+=blockDim.x*gridDim.x ){
    for ( int d=0; d<1; d++ ){
      arg4[n+d]=ZERO_double;
    }

    //user-supplied kernel call
    update_gpu(arg0+n,
           arg1+n,
           arg2+n,
           arg3+n*1,
           arg4+n*1);
  }

  //global reductions

}


//host stub function
void op_par_loop_update(char const *name, op_set set,
  op_arg arg0,
  op_arg arg1,
  op_arg arg2,
  op_arg arg3,
  op_arg arg4){

  double*arg4h = (double *)arg4.data;
  int nargs = 5;
  op_arg args[5];

  args[0] = arg0;
  args[1] = arg1;
  args[2] = arg2;
  args[3] = arg3;
  args[4] = arg4;

  // initialise timers
  double cpu_t1, cpu_t2, wall_t1, wall_t2;
  op_timing_realloc(4);
  op_timers_core(&cpu_t1, &wall_t1);
  OP_kernels[4].name      = name;
  OP_kernels[4].count    += 1;


  if (OP_diags>2) {
    printf(" kernel routine w/o indirection:  update");
  }

  int set_size = op_mpi_halo_exchanges_cuda(set, nargs, args);
  if (set->size > 0) {

    if ((OP_kernels[4].count==1) || (direct_update_stride_OP2HOST != getSetSizeFromOpArg(&arg0))) {
      direct_update_stride_OP2HOST = getSetSizeFromOpArg(&arg0);
      cudaMemcpyToSymbol(direct_update_stride_OP2CONSTANT,&direct_update_stride_OP2HOST,sizeof(int));
    }
    //set CUDA execution parameters
    #ifdef OP_BLOCK_SIZE_4
      int nthread = OP_BLOCK_SIZE_4;
    #else
      int nthread = OP_block_size;
    #endif

    int nblocks = 200;

    //transfer global reduction data to GPU
    int reduct_bytes = 0;
    int reduct_size  = 0;
    reduct_bytes += ROUND_UP(set_size*arg4.size);
    reduct_size   = MAX(reduct_size,sizeof(double));
    reallocReductArrays(reduct_bytes);
    reduct_bytes = 0;
    arg4.data   = OP_reduct_h + reduct_bytes;
    arg4.data_d = OP_reduct_d + reduct_bytes;
    reduct_bytes += ROUND_UP(set_size*arg4.size);

    int nshared = reduct_size*nthread;
    op_cuda_update<<<nblocks,nthread,nshared>>>(
      (double *) arg0.data_d,
      (double *) arg1.data_d,
      (double *) arg2.data_d,
      (double *) arg3.data_d,
      (double *) arg4.data_d,
      set->size );
    //transfer global reduction data back to CPU
    mvReductArraysToHost(reduct_bytes);
    reprLocalSum(&arg4,set_size,(double*)arg4.data);
    arg4.data = (char *)arg4h;
    op_mpi_repr_inc_reduce_double(&arg4,(double*)arg4.data);
  }
  op_mpi_set_dirtybit_cuda(nargs, args);
  cutilSafeCall(cudaDeviceSynchronize());
  //update kernel record
  op_timers_core(&cpu_t2, &wall_t2);
  OP_kernels[4].time     += wall_t2 - wall_t1;
  OP_kernels[4].transfer += (float)set->size * arg0.size;
  OP_kernels[4].transfer += (float)set->size * arg1.size * 2.0f;
  OP_kernels[4].transfer += (float)set->size * arg2.size * 2.0f;
  OP_kernels[4].transfer += (float)set->size * arg3.size;
}
