//
// auto-generated by op2.py
//

// global constants

// header
#include "op_lib_c.h"

void op_decl_const_char(int dim, char const *type,
int size, char *dat, char const *name){}
// user kernel files
#include "res_calc_acckernel.c"
#include "update_acckernel.c"
