include ../../../makefiles/common.mk

APP_NAME := gbl_tests
APP_SRC := gbl_tests.cpp

VARIANT_FILTER_OUT := mpi_%

include ../../../makefiles/c_app.mk

APP_NAME := gbl_tests_par

VARIANT_FILTER := mpi_%

include ../../../makefiles/c_app.mk
