!
! auto-generated by op2.py on 2013-05-10 11:31
!

MODULE ADT_CALC_MODULE
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE OP2_CONSTANTS

#ifdef _OPENMP
  USE OMP_LIB
#endif

CONTAINS

! user function
#include "adt_calc.inc"


SUBROUTINE adt_calc_host( userSubroutine, set, &
  & opArg1, &
  & opArg2, &
  & opArg3, &
  & opArg4, &
  & opArg5, &
  & opArg6, &
  & opArg7 )

  IMPLICIT NONE
  character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
  type ( op_set ) , INTENT(IN) :: set

  type ( op_arg ) , INTENT(IN) :: opArg1
  type ( op_arg ) , INTENT(IN) :: opArg2
  type ( op_arg ) , INTENT(IN) :: opArg3
  type ( op_arg ) , INTENT(IN) :: opArg4
  type ( op_arg ) , INTENT(IN) :: opArg5
  type ( op_arg ) , INTENT(IN) :: opArg6
  type ( op_arg ) , INTENT(IN) :: opArg7

  type ( op_arg ) , DIMENSION(7) :: opArgArray
  INTEGER(kind=4) :: numberOfOpDats
  INTEGER(kind=4) :: n_upper
  type ( op_set_core ) , POINTER :: opSetCore

  INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat1Map
  INTEGER(kind=4) :: opDat1MapDim
  real(8), POINTER, DIMENSION(:) :: opDat1Local
  INTEGER(kind=4) :: opDat1Cardinality

  INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat2Map
  INTEGER(kind=4) :: opDat2MapDim
  real(8), POINTER, DIMENSION(:) :: opDat2Local
  INTEGER(kind=4) :: opDat2Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat6Local
  INTEGER(kind=4) :: opDat6Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat7Local
  INTEGER(kind=4) :: opDat7Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat1OptPtr
  INTEGER(kind=4) :: threadID
  INTEGER(kind=4) :: numberOfThreads
  LOGICAL :: firstTime_adt_calc = .TRUE.
  type ( c_ptr )  :: planRet_adt_calc
  type ( op_plan ) , POINTER :: actualPlan_adt_calc
  INTEGER(kind=4), POINTER, DIMENSION(:) :: ncolblk_adt_calc
  INTEGER(kind=4), POINTER, DIMENSION(:) :: blkmap_adt_calc
  INTEGER(kind=4), POINTER, DIMENSION(:) :: nelems_adt_calc
  INTEGER(kind=4), POINTER, DIMENSION(:) :: offset_adt_calc
  INTEGER(kind=4), DIMENSION(1:7) :: indirectionDescriptorArray
  INTEGER(kind=4) :: numberOfIndirectOpDats
  INTEGER(kind=4) :: blockOffset
  INTEGER(kind=4) :: nblocks
  INTEGER(kind=4) :: partitionSize
  INTEGER(kind=4) :: blockID
  INTEGER(kind=4) :: nelem
  INTEGER(kind=4) :: offset_b


  INTEGER(kind=4) :: i1,i2,n

  numberOfOpDats = 7

  opArgArray(1) = opArg1
  opArgArray(2) = opArg2
  opArgArray(3) = opArg3
  opArgArray(4) = opArg4
  opArgArray(5) = opArg5
  opArgArray(6) = opArg6
  opArgArray(7) = opArg7

  n_upper = op_mpi_halo_exchanges(set%setCPtr,numberOfOpDats,opArgArray)
#ifdef OP_PART_SIZE_1
  partitionSize = OP_PART_SIZE_1
#else
  partitionSize = 0
#endif

#ifdef _OPENMP
  numberOfThreads = omp_get_max_threads()
#else
  numberOfThreads = 1
#endif
    indirectionDescriptorArray(1) = 0
    indirectionDescriptorArray(2) = 1
    indirectionDescriptorArray(3) = 1
    indirectionDescriptorArray(4) = 1
    indirectionDescriptorArray(5) = 1
    indirectionDescriptorArray(6) = -1
    indirectionDescriptorArray(7) = -1

    numberOfIndirectOpDats = 2

    planRet_adt_calc = FortranPlanCaller( &
    & userSubroutine//C_NULL_CHAR, &
    & set%setCPtr, &
    & partitionSize, &
    & numberOfOpDats, &
    & opArgArray, &
    & numberOfIndirectOpDats, &
    & indirectionDescriptorArray)

    CALL c_f_pointer(planRet_adt_calc,actualPlan_adt_calc)
    CALL c_f_pointer(actualPlan_adt_calc%ncolblk,ncolblk_adt_calc,(/set%setPtr%size/))
    CALL c_f_pointer(actualPlan_adt_calc%blkmap,blkmap_adt_calc,(/actualPlan_adt_calc%nblocks/))
    CALL c_f_pointer(actualPlan_adt_calc%offset,offset_adt_calc,(/actualPlan_adt_calc%nblocks/))
    CALL c_f_pointer(actualPlan_adt_calc%nelems,nelems_adt_calc,(/actualPlan_adt_calc%nblocks/))

    opSetCore => set%setPtr

    opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
    opDat1MapDim = getMapDimFromOpArg(opArg1)
    opDat2Cardinality = opArg2%dim * getSetSizeFromOpArg(opArg2)
    opDat2MapDim = getMapDimFromOpArg(opArg2)
    opDat6Cardinality = opArg6%dim * getSetSizeFromOpArg(opArg6)
    opDat7Cardinality = opArg7%dim * getSetSizeFromOpArg(opArg7)
    CALL c_f_pointer(opArg1%data,opDat1Local,(/opDat1Cardinality/))
    CALL c_f_pointer(opArg1%map_data,opDat1Map,(/opSetCore%size*opDat1MapDim/))
    CALL c_f_pointer(opArg2%data,opDat2Local,(/opDat2Cardinality/))
    CALL c_f_pointer(opArg2%map_data,opDat2Map,(/opSetCore%size*opDat2MapDim/))
    CALL c_f_pointer(opArg6%data,opDat6Local,(/opDat6Cardinality/))
    CALL c_f_pointer(opArg7%data,opDat7Local,(/opDat7Cardinality/))


    blockOffset = 0

    DO i1 = 0, actualPlan_adt_calc%ncolors-1, 1
      IF (i1 .EQ. actualPlan_adt_calc%ncolors_core) THEN
        CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
      END IF

      nblocks = ncolblk_adt_calc(i1 + 1)
      !$OMP PARALLEL DO private (threadID, blockID, nelem, offset_b, opDat1OptPtr)
      DO i2 = 0, nblocks-1, 1
        threadID = omp_get_thread_num()
        blockID = blkmap_adt_calc(i2+blockOffset+1)
        nelem = nelems_adt_calc(blockID+1)
        offset_b = offset_adt_calc(blockID+1)
        DO n = 0, nelem-1, 1
          IF (opArg1%opt == 1) THEN
            opDat1OptPtr => opDat1Local(1 + opDat1Map(1 + (n+offset_b) * opDat1MapDim + 0) * (2):)
          ELSE
            opDat1OptPtr => opDat1Local(1:)
          END IF
! kernel call
        CALL adt_calc( &
          & opDat1OptPtr(1:2), &
          & opDat2Local(1 + opDat2Map(1 + (n+offset_b) * opDat2MapDim + 0) * (2) : opDat2Map(1 + (n+offset_b) * opDat2MapDim + 0) * (2) + 2), &
          & opDat2Local(1 + opDat2Map(1 + (n+offset_b) * opDat2MapDim + 1) * (2) : opDat2Map(1 + (n+offset_b) * opDat2MapDim + 1) * (2) + 2), &
          & opDat2Local(1 + opDat2Map(1 + (n+offset_b) * opDat2MapDim + 2) * (2) : opDat2Map(1 + (n+offset_b) * opDat2MapDim + 2) * (2) + 2), &
          & opDat2Local(1 + opDat2Map(1 + (n+offset_b) * opDat2MapDim + 3) * (2) : opDat2Map(1 + (n+offset_b) * opDat2MapDim + 3) * (2) + 2), &
          & opDat6Local(1 + (n+offset_b) * (4) : (n+offset_b) * (4) + 4), &
          & opDat7Local(1 + (n+offset_b)) &
          & )
        END DO
      END DO
      !$OMP END PARALLEL DO
      blockOffset = blockOffset + nblocks
    END DO
    IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
      CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
    END IF


    CALL op_mpi_set_dirtybit(numberOfOpDats,opArgArray)

  END SUBROUTINE
  END MODULE