!
! auto-generated by op2_fortran.py on 2013-03-06 17:52
!

program AIRFOIL
  use OP2_FORTRAN_DECLARATIONS
  use OP2_FORTRAN_HDF5_DECLARATIONS
  use SAVE_SOLN_MODULE
  use ADT_CALC_MODULE
  use RES_CALC_MODULE
  use BRES_CALC_MODULE
  use UPDATE_MODULE
  use OP2_Fortran_RT_Support
  !use AIRFOIL_SEQ
  use OP2_CONSTANTS
  use IO
  use, intrinsic :: ISO_C_BINDING

  implicit none

  intrinsic :: sqrt, real

  integer(4) :: iter, k, i

  integer(4), parameter :: maxnode = 9900
  integer(4), parameter :: maxcell = (9702+1)
  integer(4), parameter :: maxedge = 19502

  integer(4), parameter :: iterationNumber = 1000

  integer(4) :: nnode, ncell, nbedge, nedge, niter, qdim
  real(8) :: ncellr

  ! profiling
  real(kind=c_double) :: startTime = 0
  real(kind=c_double) :: endTime = 0

  ! integer references (valid inside the OP2 library) for op_set
  type(op_set) :: nodes, edges, bedges, cells

  ! integer references (valid inside the OP2 library) for pointers between data sets
  type(op_map) :: pedge, pecell, pcell, pbedge, pbecell

  ! integer reference (valid inside the OP2 library) for op_data
  type(op_dat) :: p_bound, p_x, p_q, p_qold, p_adt, p_res

  ! arrays used in data
  integer(4), dimension(:), allocatable, target :: ecell, bound, edge, bedge, becell, cell
  real(8) :: rms

  integer(4) :: debugiter, retDebug
  real(8) :: datad

  ! OP initialisation

  call op_init (0)
  call op_print ("Initialising OP2")

  ! declare sets, pointers, datasets and global constants (for now, no new partition info)
  call op_print ("Declaring OP2 sets")
  call op_decl_set_hdf5 ( nnode, nodes, 'new_grid.h5', 'nodes' )
  call op_decl_set_hdf5 ( nedge, edges, 'new_grid.h5', 'edges' )
  call op_decl_set_hdf5 ( nbedge, bedges, 'new_grid.h5', 'bedges' )
  call op_decl_set_hdf5 ( ncell, cells, 'new_grid.h5', 'cells' )

  call op_print ("Declaring OP2 maps")
  call op_decl_map_hdf5 ( edges, nodes, 2, pedge, 'new_grid.h5', 'pedge' )
  call op_decl_map_hdf5 ( edges, cells, 2, pecell, 'new_grid.h5', 'pecell' )
  call op_decl_map_hdf5 ( bedges, nodes, 2, pbedge, 'new_grid.h5', 'pbedge' )
  call op_decl_map_hdf5 ( bedges, cells, 1, pbecell, 'new_grid.h5', 'pbecell' )
  call op_decl_map_hdf5 ( cells, nodes, 4, pcell, 'new_grid.h5', 'pcell' )

  call op_print ("Declaring OP2 data")
  call op_decl_dat_hdf5 ( bedges, 1, p_bound, 'int', 'new_grid.h5', 'p_bound' )
  call op_decl_dat_hdf5 ( nodes, 2, p_x, 'double', 'new_grid.h5', 'p_x' )
  call op_decl_dat_hdf5 ( cells, 4, p_q, 'double', 'new_grid.h5', 'p_q' )
  call op_decl_dat_hdf5 ( cells, 4, p_qold, 'double', 'new_grid.h5', 'p_qold' )
  call op_decl_dat_hdf5 ( cells, 1, p_adt, 'double', 'new_grid.h5', 'p_adt' )
  call op_decl_dat_hdf5 ( cells, 4, p_res, 'double', 'new_grid.h5', 'p_res' )

  call op_print ("Declaring OP2 constants")

  call op_print ('Initialising constants')
  call initialise_constants ( )

  call op_write_hdf5("new_grid_out.h5");

  call op_partition ('PARMETIS','KWAY', edges, pecell, p_x)
  ncellr = real(op_get_size(cells))
  print *, "ncellr", ncellr

  ! start timer
  call op_timers ( startTime )

  ! main time-marching loop

  do niter = 1, iterationNumber

     call save_soln_host("save_soln",cells,  &
                      & op_arg_dat(p_q,-1,OP_ID,4,"real(8)",OP_READ),  &
                      & op_arg_dat(p_qold,-1,OP_ID,4,"real(8)",OP_WRITE))


    ! predictor/corrector update loop

    do k = 1, 2

      ! calculate area/timstep
      call adt_calc_host("adt_calc",cells,  &
                       & op_arg_dat(p_x,1,pcell,2,"real(8)",OP_READ),  &
                       & op_arg_dat(p_x,2,pcell,2,"real(8)",OP_READ),  &
                       & op_arg_dat(p_x,3,pcell,2,"real(8)",OP_READ),  &
                       & op_arg_dat(p_x,4,pcell,2,"real(8)",OP_READ),  &
                       & op_arg_dat(p_q,-1,OP_ID,4,"real(8)",OP_READ),  &
                       & op_arg_dat(p_adt,-1,OP_ID,1,"real(8)",OP_WRITE))


      ! calculate flux residual
      call res_calc_host("res_calc",edges,  &
                       & op_arg_dat(p_x,1,pedge,2,"real(8)",OP_READ),  &
                       & op_arg_dat(p_x,2,pedge,2,"real(8)",OP_READ),  &
                       & op_arg_dat(p_q,1,pecell,4,"real(8)",OP_READ),  &
                       & op_arg_dat(p_q,2,pecell,4,"real(8)",OP_READ),  &
                       & op_arg_dat(p_adt,1,pecell,1,"real(8)",OP_READ),  &
                       & op_arg_dat(p_adt,2,pecell,1,"real(8)",OP_READ),  &
                       & op_opt_arg_dat(.TRUE.,p_res,1,pecell,4,"real(8)",OP_INC),  &
                       & op_arg_dat(p_res,2,pecell,4,"real(8)",OP_INC))


      call bres_calc_host("bres_calc",bedges,  &
                       & op_arg_dat(p_x,1,pbedge,2,"real(8)",OP_READ),  &
                       & op_arg_dat(p_x,2,pbedge,2,"real(8)",OP_READ),  &
                       & op_arg_dat(p_q,1,pbecell,4,"real(8)",OP_READ),  &
                       & op_arg_dat(p_adt,1,pbecell,1,"real(8)",OP_READ),  &
                       & op_arg_dat(p_res,1,pbecell,4,"real(8)",OP_INC),  &
                       & op_arg_dat(p_bound,-1,OP_ID,1,"integer(4)",OP_READ))


      ! update flow field

      rms = 0.0

      call update_host("update",cells,  &
                       & op_arg_dat(p_qold,-1,OP_ID,4,"real(8)",OP_READ),  &
                       & op_arg_dat(p_q,-1,OP_ID,4,"real(8)",OP_WRITE),  &
                       & op_arg_dat(p_res,-1,OP_ID,4,"real(8)",OP_RW),  &
                       & op_arg_dat(p_adt,-1,OP_ID,1,"real(8)",OP_READ),  &
                       & op_arg_gbl(rms,1,"real(8)",OP_INC))



    end do ! internal loop

    rms = sqrt ( rms / ncellr )

    if (mod(niter,100) .eq. 0) then
      if (op_is_root() .eq. 1) then
        write (*,*) niter,"  ",rms
      end if
    end if

  end do ! external loop

  call op_timers ( endTime )
  !if (op_is_root() .eq. 1) then
    call op_timing_output ()
    write (*,*) 'Max total runtime =', endTime - startTime,'seconds'
  !end if

  call op_exit (  )
end program AIRFOIL
