!
! auto-generated by op2.py on 2013-05-10 11:31
!

MODULE BRES_CALC_MODULE
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE OP2_CONSTANTS

#ifdef _OPENMP
  USE OMP_LIB
#endif

CONTAINS

! user function
#include "bres_calc.inc"


SUBROUTINE bres_calc_host( userSubroutine, set, &
  & opArg1, &
  & opArg2, &
  & opArg3, &
  & opArg4, &
  & opArg5, &
  & opArg6, &
  & opArg7 )

  IMPLICIT NONE
  character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
  type ( op_set ) , INTENT(IN) :: set

  type ( op_arg ) , INTENT(IN) :: opArg1
  type ( op_arg ) , INTENT(IN) :: opArg2
  type ( op_arg ) , INTENT(IN) :: opArg3
  type ( op_arg ) , INTENT(IN) :: opArg4
  type ( op_arg ) , INTENT(IN) :: opArg5
  type ( op_arg ) , INTENT(IN) :: opArg6
  type ( op_arg ) , INTENT(IN) :: opArg7

  type ( op_arg ) , DIMENSION(7) :: opArgArray
  INTEGER(kind=4) :: numberOfOpDats
  INTEGER(kind=4) :: n_upper
  type ( op_set_core ) , POINTER :: opSetCore

  INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat2Map
  INTEGER(kind=4) :: opDat2MapDim
  real(8), POINTER, DIMENSION(:) :: opDat2Local
  INTEGER(kind=4) :: opDat2Cardinality

  INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat4Map
  INTEGER(kind=4) :: opDat4MapDim
  real(8), POINTER, DIMENSION(:) :: opDat4Local
  INTEGER(kind=4) :: opDat4Cardinality

  INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat5Map
  INTEGER(kind=4) :: opDat5MapDim
  real(8), POINTER, DIMENSION(:) :: opDat5Local
  INTEGER(kind=4) :: opDat5Cardinality

  INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat6Map
  INTEGER(kind=4) :: opDat6MapDim
  real(8), POINTER, DIMENSION(:) :: opDat6Local
  INTEGER(kind=4) :: opDat6Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat1Local
  integer(4), POINTER, DIMENSION(:) :: opDat7Local
  INTEGER(kind=4) :: opDat7Cardinality

  INTEGER(kind=4) :: threadID
  INTEGER(kind=4) :: numberOfThreads
  LOGICAL :: firstTime_bres_calc = .TRUE.
  type ( c_ptr )  :: planRet_bres_calc
  type ( op_plan ) , POINTER :: actualPlan_bres_calc
  INTEGER(kind=4), POINTER, DIMENSION(:) :: ncolblk_bres_calc
  INTEGER(kind=4), POINTER, DIMENSION(:) :: blkmap_bres_calc
  INTEGER(kind=4), POINTER, DIMENSION(:) :: nelems_bres_calc
  INTEGER(kind=4), POINTER, DIMENSION(:) :: offset_bres_calc
  INTEGER(kind=4), DIMENSION(1:7) :: indirectionDescriptorArray
  INTEGER(kind=4) :: numberOfIndirectOpDats
  INTEGER(kind=4) :: blockOffset
  INTEGER(kind=4) :: nblocks
  INTEGER(kind=4) :: partitionSize
  INTEGER(kind=4) :: blockID
  INTEGER(kind=4) :: nelem
  INTEGER(kind=4) :: offset_b


  INTEGER(kind=4) :: i1,i2,n

  numberOfOpDats = 7

  opArgArray(1) = opArg1
  opArgArray(2) = opArg2
  opArgArray(3) = opArg3
  opArgArray(4) = opArg4
  opArgArray(5) = opArg5
  opArgArray(6) = opArg6
  opArgArray(7) = opArg7

  n_upper = op_mpi_halo_exchanges(set%setCPtr,numberOfOpDats,opArgArray)
#ifdef OP_PART_SIZE_1
  partitionSize = OP_PART_SIZE_1
#else
  partitionSize = 0
#endif

#ifdef _OPENMP
  numberOfThreads = omp_get_max_threads()
#else
  numberOfThreads = 1
#endif
    indirectionDescriptorArray(1) = -1
    indirectionDescriptorArray(2) = 0
    indirectionDescriptorArray(3) = 0
    indirectionDescriptorArray(4) = 1
    indirectionDescriptorArray(5) = 2
    indirectionDescriptorArray(6) = 3
    indirectionDescriptorArray(7) = -1

    numberOfIndirectOpDats = 4

    planRet_bres_calc = FortranPlanCaller( &
    & userSubroutine//C_NULL_CHAR, &
    & set%setCPtr, &
    & partitionSize, &
    & numberOfOpDats, &
    & opArgArray, &
    & numberOfIndirectOpDats, &
    & indirectionDescriptorArray)

    CALL c_f_pointer(planRet_bres_calc,actualPlan_bres_calc)
    CALL c_f_pointer(actualPlan_bres_calc%ncolblk,ncolblk_bres_calc,(/set%setPtr%size/))
    CALL c_f_pointer(actualPlan_bres_calc%blkmap,blkmap_bres_calc,(/actualPlan_bres_calc%nblocks/))
    CALL c_f_pointer(actualPlan_bres_calc%offset,offset_bres_calc,(/actualPlan_bres_calc%nblocks/))
    CALL c_f_pointer(actualPlan_bres_calc%nelems,nelems_bres_calc,(/actualPlan_bres_calc%nblocks/))

    opSetCore => set%setPtr

    opDat2Cardinality = opArg2%dim * getSetSizeFromOpArg(opArg2)
    opDat2MapDim = getMapDimFromOpArg(opArg2)
    opDat4Cardinality = opArg4%dim * getSetSizeFromOpArg(opArg4)
    opDat4MapDim = getMapDimFromOpArg(opArg4)
    opDat5Cardinality = opArg5%dim * getSetSizeFromOpArg(opArg5)
    opDat5MapDim = getMapDimFromOpArg(opArg5)
    opDat6Cardinality = opArg6%dim * getSetSizeFromOpArg(opArg6)
    opDat6MapDim = getMapDimFromOpArg(opArg6)
    opDat7Cardinality = opArg7%dim * getSetSizeFromOpArg(opArg7)
    CALL c_f_pointer(opArg2%data,opDat2Local,(/opDat2Cardinality/))
    CALL c_f_pointer(opArg2%map_data,opDat2Map,(/opSetCore%size*opDat2MapDim/))
    CALL c_f_pointer(opArg4%data,opDat4Local,(/opDat4Cardinality/))
    CALL c_f_pointer(opArg4%map_data,opDat4Map,(/opSetCore%size*opDat4MapDim/))
    CALL c_f_pointer(opArg5%data,opDat5Local,(/opDat5Cardinality/))
    CALL c_f_pointer(opArg5%map_data,opDat5Map,(/opSetCore%size*opDat5MapDim/))
    CALL c_f_pointer(opArg6%data,opDat6Local,(/opDat6Cardinality/))
    CALL c_f_pointer(opArg6%map_data,opDat6Map,(/opSetCore%size*opDat6MapDim/))
    CALL c_f_pointer(opArg1%data,opDat1Local, (/opArg1%dim/))
    CALL c_f_pointer(opArg7%data,opDat7Local,(/opDat7Cardinality/))


    blockOffset = 0

    DO i1 = 0, actualPlan_bres_calc%ncolors-1, 1
      IF (i1 .EQ. actualPlan_bres_calc%ncolors_core) THEN
        CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
      END IF

      nblocks = ncolblk_bres_calc(i1 + 1)
      !$OMP PARALLEL DO private (threadID, blockID, nelem, offset_b)
      DO i2 = 0, nblocks-1, 1
        threadID = omp_get_thread_num()
        blockID = blkmap_bres_calc(i2+blockOffset+1)
        nelem = nelems_bres_calc(blockID+1)
        offset_b = offset_bres_calc(blockID+1)
        DO n = 0, nelem-1, 1
! kernel call
        CALL bres_calc( &
          & opDat1Local, &
          & opDat2Local(1 + opDat2Map(1 + (n+offset_b) * opDat2MapDim + 0) * (2) : opDat2Map(1 + (n+offset_b) * opDat2MapDim + 0) * (2) + 2), &
          & opDat2Local(1 + opDat2Map(1 + (n+offset_b) * opDat2MapDim + 1) * (2) : opDat2Map(1 + (n+offset_b) * opDat2MapDim + 1) * (2) + 2), &
          & opDat4Local(1 + opDat4Map(1 + (n+offset_b) * opDat4MapDim + 0) * (4) : opDat4Map(1 + (n+offset_b) * opDat4MapDim + 0) * (4) + 4), &
          & opDat5Local(1 + opDat5Map(1 + (n+offset_b) * opDat5MapDim + 0)), &
          & opDat6Local(1 + opDat6Map(1 + (n+offset_b) * opDat6MapDim + 0) * (4) : opDat6Map(1 + (n+offset_b) * opDat6MapDim + 0) * (4) + 4), &
          & opDat7Local(1 + (n+offset_b)) &
          & )
        END DO
      END DO
      !$OMP END PARALLEL DO
      blockOffset = blockOffset + nblocks
    END DO
    IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
      CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
    END IF


    CALL op_mpi_set_dirtybit(numberOfOpDats,opArgArray)

  END SUBROUTINE
  END MODULE