include ../../../makefiles/common.mk

APP_NAME := min_direct
APP_SRC := min_direct.cpp

VARIANT_FILTER_OUT := mpi_%

include ../../../makefiles/c_app.mk

APP_NAME := min_indirect
APP_SRC := min_indirect.cpp

VARIANT_FILTER_OUT := mpi_%

include ../../../makefiles/c_app.mk
