//
// auto-generated by op2.py
//

// header
#include "op_lib_cpp.h"

// global constants

void op_decl_const_char(int dim, char const *type,
  int size, char *dat, char const *name){

}
// user kernel files
#include "res_calc_omp4kernel_func.cpp"
#include "update_omp4kernel_func.cpp"
