!
! auto-generated by op2.py on 2013-06-17 11:37
!

MODULE RES_CALC_MODULE
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE OP2_CONSTANTS

#ifdef _OPENMP
  USE OMP_LIB
#endif
REAL(kind=4) :: loopTimeHostres_calc
REAL(kind=4) :: loopTimeKernelres_calc
INTEGER(kind=4) :: numberCalledres_calc


CONTAINS

! user function
#include "res_calc.inc"


SUBROUTINE op_wrap_res_calc( &
  & opDat1Local, &
  & opDat3Local, &
  & opDat5Local, &
  & opDat7Local, &
  & opDat1Map, &
  & opDat1MapDim, &
  & opDat3Map, &
  & opDat3MapDim, &
  & bottom,top)
  real(8) opDat1Local(2,*)
  real(8) opDat3Local(4,*)
  real(8) opDat5Local(1,*)
  real(8) opDat7Local(4,*)
  INTEGER(kind=4) opDat1Map(*)
  INTEGER(kind=4) opDat1MapDim
  INTEGER(kind=4) opDat3Map(*)
  INTEGER(kind=4) opDat3MapDim
  INTEGER(kind=4) bottom,top,i1
  INTEGER(kind=4) map1idx, map2idx, map3idx, map4idx

  DO i1 = bottom, top-1, 1
    map1idx = opDat1Map(1 + i1 * opDat1MapDim + 0)+1
    map2idx = opDat1Map(1 + i1 * opDat1MapDim + 1)+1
    map3idx = opDat3Map(1 + i1 * opDat3MapDim + 0)+1
    map4idx = opDat3Map(1 + i1 * opDat3MapDim + 1)+1
! kernel call
  CALL res_calc( &
    & opDat1Local(1,map1idx), &
    & opDat1Local(1,map2idx), &
    & opDat3Local(1,map3idx), &
    & opDat3Local(1,map4idx), &
    & opDat5Local(1,map3idx), &
    & opDat5Local(1,map4idx), &
    & opDat7Local(1,map3idx), &
    & opDat7Local(1,map4idx) &
    & )
  END DO
END SUBROUTINE
SUBROUTINE res_calc_host( userSubroutine, set, &
  & opArg1, &
  & opArg2, &
  & opArg3, &
  & opArg4, &
  & opArg5, &
  & opArg6, &
  & opArg7, &
  & opArg8 )

  IMPLICIT NONE
  character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
  type ( op_set ) , INTENT(IN) :: set

  type ( op_arg ) , INTENT(IN) :: opArg1
  type ( op_arg ) , INTENT(IN) :: opArg2
  type ( op_arg ) , INTENT(IN) :: opArg3
  type ( op_arg ) , INTENT(IN) :: opArg4
  type ( op_arg ) , INTENT(IN) :: opArg5
  type ( op_arg ) , INTENT(IN) :: opArg6
  type ( op_arg ) , INTENT(IN) :: opArg7
  type ( op_arg ) , INTENT(IN) :: opArg8

  type ( op_arg ) , DIMENSION(8) :: opArgArray
  INTEGER(kind=4) :: numberOfOpDats
  INTEGER(kind=4) :: n_upper
  type ( op_set_core ) , POINTER :: opSetCore

  INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat1Map
  INTEGER(kind=4) :: opDat1MapDim
  real(8), POINTER, DIMENSION(:) :: opDat1Local
  INTEGER(kind=4) :: opDat1Cardinality

  INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat3Map
  INTEGER(kind=4) :: opDat3MapDim
  real(8), POINTER, DIMENSION(:) :: opDat3Local
  INTEGER(kind=4) :: opDat3Cardinality

  INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat5Map
  INTEGER(kind=4) :: opDat5MapDim
  real(8), POINTER, DIMENSION(:) :: opDat5Local
  INTEGER(kind=4) :: opDat5Cardinality

  INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat7Map
  INTEGER(kind=4) :: opDat7MapDim
  real(8), POINTER, DIMENSION(:) :: opDat7Local
  INTEGER(kind=4) :: opDat7Cardinality

  INTEGER(kind=4) :: threadID
  INTEGER(kind=4) :: numberOfThreads
  INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
  INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
  REAL(kind=8) :: startTimeHost
  REAL(kind=8) :: endTimeHost
  REAL(kind=8) :: startTimeKernel
  REAL(kind=8) :: endTimeKernel
  REAL(kind=8) :: accumulatorHostTime
  REAL(kind=8) :: accumulatorKernelTime
  INTEGER(kind=4) :: returnSetKernelTiming
  LOGICAL :: firstTime_res_calc = .TRUE.
  type ( c_ptr )  :: planRet_res_calc
  type ( op_plan ) , POINTER :: actualPlan_res_calc
  INTEGER(kind=4), POINTER, DIMENSION(:) :: ncolblk_res_calc
  INTEGER(kind=4), POINTER, DIMENSION(:) :: blkmap_res_calc
  INTEGER(kind=4), POINTER, DIMENSION(:) :: nelems_res_calc
  INTEGER(kind=4), POINTER, DIMENSION(:) :: offset_res_calc
  INTEGER(kind=4), DIMENSION(1:8) :: indirectionDescriptorArray
  INTEGER(kind=4) :: numberOfIndirectOpDats
  INTEGER(kind=4) :: blockOffset
  INTEGER(kind=4) :: nblocks
  INTEGER(kind=4) :: partitionSize
  INTEGER(kind=4) :: blockID
  INTEGER(kind=4) :: nelem
  INTEGER(kind=4) :: offset_b


  INTEGER(kind=4) :: i1,i2,n

  numberOfOpDats = 8

  opArgArray(1) = opArg1
  opArgArray(2) = opArg2
  opArgArray(3) = opArg3
  opArgArray(4) = opArg4
  opArgArray(5) = opArg5
  opArgArray(6) = opArg6
  opArgArray(7) = opArg7
  opArgArray(8) = opArg8

  n_upper = op_mpi_halo_exchanges(set%setCPtr,numberOfOpDats,opArgArray)
  numberCalledres_calc = numberCalledres_calc+ 1

  call date_and_time(values=timeArrayStart)
  startTimeHost = 1.00000 * timeArrayStart(8) + &
  & 1000.00 * timeArrayStart(7) + &
  & 60000 * timeArrayStart(6) + &
  & 3600000 * timeArrayStart(5)

#ifdef OP_PART_SIZE_1
  partitionSize = OP_PART_SIZE_1
#else
  partitionSize = 0
#endif

#ifdef _OPENMP
  numberOfThreads = omp_get_max_threads()
#else
  numberOfThreads = 1
#endif
    indirectionDescriptorArray(1) = 0
    indirectionDescriptorArray(2) = 0
    indirectionDescriptorArray(3) = 1
    indirectionDescriptorArray(4) = 1
    indirectionDescriptorArray(5) = 2
    indirectionDescriptorArray(6) = 2
    indirectionDescriptorArray(7) = 3
    indirectionDescriptorArray(8) = 3

    numberOfIndirectOpDats = 4

    planRet_res_calc = FortranPlanCaller( &
    & userSubroutine//C_NULL_CHAR, &
    & set%setCPtr, &
    & partitionSize, &
    & numberOfOpDats, &
    & opArgArray, &
    & numberOfIndirectOpDats, &
    & indirectionDescriptorArray)

    CALL c_f_pointer(planRet_res_calc,actualPlan_res_calc)
    CALL c_f_pointer(actualPlan_res_calc%ncolblk,ncolblk_res_calc,(/actualPlan_res_calc%ncolors_core/))
    CALL c_f_pointer(actualPlan_res_calc%blkmap,blkmap_res_calc,(/actualPlan_res_calc%nblocks/))
    CALL c_f_pointer(actualPlan_res_calc%offset,offset_res_calc,(/actualPlan_res_calc%nblocks/))
    CALL c_f_pointer(actualPlan_res_calc%nelems,nelems_res_calc,(/actualPlan_res_calc%nblocks/))

    opSetCore => set%setPtr

    opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
    opDat1MapDim = getMapDimFromOpArg(opArg1)
    opDat3Cardinality = opArg3%dim * getSetSizeFromOpArg(opArg3)
    opDat3MapDim = getMapDimFromOpArg(opArg3)
    opDat5Cardinality = opArg5%dim * getSetSizeFromOpArg(opArg5)
    opDat5MapDim = getMapDimFromOpArg(opArg5)
    opDat7Cardinality = opArg7%dim * getSetSizeFromOpArg(opArg7)
    opDat7MapDim = getMapDimFromOpArg(opArg7)
    CALL c_f_pointer(opArg1%data,opDat1Local,(/opDat1Cardinality/))
    CALL c_f_pointer(opArg1%map_data,opDat1Map,(/opSetCore%size*opDat1MapDim/))
    CALL c_f_pointer(opArg3%data,opDat3Local,(/opDat3Cardinality/))
    CALL c_f_pointer(opArg3%map_data,opDat3Map,(/opSetCore%size*opDat3MapDim/))
    CALL c_f_pointer(opArg5%data,opDat5Local,(/opDat5Cardinality/))
    CALL c_f_pointer(opArg5%map_data,opDat5Map,(/opSetCore%size*opDat5MapDim/))
    CALL c_f_pointer(opArg7%data,opDat7Local,(/opDat7Cardinality/))
    CALL c_f_pointer(opArg7%map_data,opDat7Map,(/opSetCore%size*opDat7MapDim/))



    call date_and_time(values=timeArrayEnd)
    endTimeHost = 1.00000 * timeArrayEnd(8) + &
    & 1000 * timeArrayEnd(7)  + &
    & 60000 * timeArrayEnd(6) + &
    & 3600000 * timeArrayEnd(5)

    accumulatorHostTime = endTimeHost - startTimeHost
    loopTimeHostres_calc = loopTimeHostres_calc + accumulatorHostTime

    call date_and_time(values=timeArrayStart)
    startTimeKernel = 1.00000 * timeArrayStart(8) + &
    & 1000 * timeArrayStart(7) + &
    & 60000 * timeArrayStart(6) + &
    & 3600000 * timeArrayStart(5)

    blockOffset = 0

    DO i1 = 0, actualPlan_res_calc%ncolors-1, 1
      IF (i1 .EQ. actualPlan_res_calc%ncolors_core) THEN
        CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
      END IF

      nblocks = ncolblk_res_calc(i1 + 1)
      !$OMP PARALLEL DO private (threadID, blockID, nelem, offset_b)
      DO i2 = 0, nblocks-1, 1
        threadID = omp_get_thread_num()
        blockID = blkmap_res_calc(i2+blockOffset+1)
        nelem = nelems_res_calc(blockID+1)
        offset_b = offset_res_calc(blockID+1)
        CALL op_wrap_res_calc( &
        & opDat1Local, &
        & opDat3Local, &
        & opDat5Local, &
        & opDat7Local, &
        & opDat1Map, &
        & opDat1MapDim, &
        & opDat3Map, &
        & opDat3MapDim, &
        & offset_b, offset_b+nelem)
      END DO
      !$OMP END PARALLEL DO
      blockOffset = blockOffset + nblocks
    END DO
    IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
      CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
    END IF


    call date_and_time(values=timeArrayEnd)
    endTimeKernel = 1.00000 * timeArrayEnd(8) + &
    & 1000 * timeArrayEnd(7) + &
    & 60000 * timeArrayEnd(6) + &
    & 3600000 * timeArrayEnd(5)

    accumulatorKernelTime = endTimeKernel - startTimeKernel
    loopTimeKernelres_calc = loopTimeKernelres_calc + accumulatorKernelTime

    call date_and_time(values=timeArrayStart)
    startTimeHost = 1.00000 * timeArrayStart(8) + &
    & 1000.00 * timeArrayStart(7) + &
    & 60000 * timeArrayStart(6) + &
    & 3600000 * timeArrayStart(5)

    CALL op_mpi_set_dirtybit(numberOfOpDats,opArgArray)

    call date_and_time(values=timeArrayEnd)
    endTimeHost = 1.00000 * timeArrayEnd(8) + &
    1000 * timeArrayEnd(7) + &
    60000 * timeArrayEnd(6) + &
    3600000 * timeArrayEnd(5)

    accumulatorHostTime = endTimeHost - startTimeHost
    loopTimeHostres_calc = loopTimeHostres_calc + accumulatorHostTime

    returnSetKernelTiming = setKernelTime(2 , userSubroutine//C_NULL_CHAR, &
    & accumulatorKernelTime / 1000.00,actualPlan_res_calc%transfer,actualPlan_res_calc%transfer2)
  END SUBROUTINE
  END MODULE