//
// auto-generated by op2.m on 30-May-2011 21:57:40
//

// header

#include <op_lib_cpp.h>
#include <op_lib_core.h>
#include <op_rt_support.h>
#include <op_cuda_rt_support.h>
#include <op_cuda_reduction.h>

// global constants

#ifndef MAX_CONST_SIZE
#define MAX_CONST_SIZE 128
#endif

__constant__ double alpha;

/*void op_decl_const_char(int dim, char const *type,
            int size, char *dat, char const *name){
  cutilSafeCall(cudaMemcpyToSymbol(name, dat, dim*size));
}*/

// user kernel files

#include "res_kernel.cu"
#include "update_kernel.cu"
