//
// auto-generated by op2.m on 16-Oct-2012 15:15:12
//

// header

#include "op_lib_cpp.h"

// global constants

extern double alpha;

// user kernel files

#include "res_kernel.cpp"
#include "update_kernel.cpp"
