//
// auto-generated by op2.py on 2015-07-08 13:58
//

// header
#include "op_lib_cpp.h"

// global constants
extern double alpha;
// user kernel files
#include "res_kernel.cpp"
#include "update_kernel.cpp"
