// 
// auto-generated by op2.m on 14-Mar-2012 14:10:51 
//

// header                     
                              
#include "op_lib_cpp.h"       
                              
// global constants           
                              
extern double alpha;          
                              
// user kernel files          
                              
#include "res_kernel.cpp"     
#include "update_kernel.cpp"  
