//
// auto-generated by op2.py on 2015-08-12 15:03
//

// header
#include "op_lib_cpp.h"

// global constants
extern double alpha;
// user kernel files
#include "res_seqkernel.cpp"
#include "update_seqkernel.cpp"
