//
// auto-generated by op2.py
//

// header
#include "user_types.h"
#include "op_lib_cpp.h"

// global constants
extern double alpha;
// user kernel files
#include "res_kernel.cpp"
#include "update_kernel.cpp"
