//
// auto-generated by op2.py
//

// global constants
extern double alpha;

// header
#include "../user_types.h"
#include "op_lib_cpp.h"

// user kernel files
#include "res_kernel.cpp"
#include "update_kernel.cpp"
