// 
// auto-generated by op2.m on 30-May-2011 21:57:40 
//

// header                   
                            
#include "op_lib.h"         
                            
void __syncthreads(){}      
                            
// global constants         
                            
extern float alpha;         
                            
// user kernel files        
                            
#include "res_kernel.cpp"   
#include "update_kernel.cpp"
