//
// auto-generated by op2.m on 29-Oct-2012 09:32:04
//

// header

#include "op_lib_cpp.h"

// global constants

extern double gam;
extern double gm1;
extern double cfl;
extern double eps;
extern double mach;
extern double alpha;
extern double qinf[4];

// user kernel files

#include "save_soln_kernel.cpp"
#include "adt_calc_kernel.cpp"
#include "res_calc_kernel.cpp"
#include "bres_calc_kernel.cpp"
#include "update_kernel.cpp"
