//
// auto-generated by op2.py
//

#ifdef _OPENMP
#include <omp.h>
#endif

// global constants

// header
#include "op_lib_cpp.h"

// user kernel files
#include "res_calc_kernel.cpp"
#include "update_kernel.cpp"
