#!/bin/bash
# e.g. mpirun -np 4 numawrap ./application

# Find the rank of the process from the MPI local rank environment variable
# to ensure unique output filenames.
if [[ -n ${OMPI_COMM_WORLD_LOCAL_RANK} ]]
    then
    let lrank=${OMPI_COMM_WORLD_LOCAL_RANK}
elif [[ -n ${MV2_COMM_WORLD_LOCAL_RANK} ]]
    then
    let lrank=${MV2_COMM_WORLD_LOCAL_RANK}
elif [[ -n ${PMI_RANK} ]]
    then
    let lrank=${PMI_RANK}
elif [[ -n ${PMI_ID} && -n ${MPISPAWN_LOCAL_NPROCS} ]]
    then
    let lrank=${PMI_ID}%${MPISPAWN_LOCAL_NPROCS}
elif [[ -n ${MPI_LOCALRANKID} ]]
    then
    let lrank=${MPI_LOCALRANKID}
else
    echo could not determine local rank
fi

export CUDA_VISIBLE_DEVICES=${lrank}

echo $lrank

# Dynamically bind to NUMA node based on local rank and number of NUMA nodes available
N_NUMA=$(numactl --hardware | grep 'available:' | awk '{print $2}')
if [[ -z "$N_NUMA" || $N_NUMA -lt 1 ]]; then
    N_NUMA=1
fi

numa_node=$(( lrank % N_NUMA ))
numactl --cpunodebind=${numa_node} ${@}
