//
// auto-generated by op2.py
//

#include "op_lib_cpp.h"
//global_constants - values #defined by JIT
#include "jit_const.h

//user function
__device__ void save_soln_gpu( const double *q, double *qold)
{
  for (int n = 0; n < 4; n++)
    qold[n] = q[n];

}

//C CUDA kernel function
__global__ void op_cuda_save_soln(
 const double* __restrict arg0,
 double* __restrict arg1,
 int set_size)
{
  //Process set elements
  for (int n = threadIdx.x+blockIdx.x*blockDim.x; n < set_size; n += blockDim.x*gridDim.x)
  {

    //user function call
    save_soln_gpu(arg0+n*4,
                  arg1+n*4
    );

  }
}

extern "C" {
void op_par_loop_save_soln_execute(op_kernel_descriptor* desc);

//Host stub function
void op_par_loop_save_soln_execute(op_kernel_descriptor* desc)
{
  op_set set = desc->set;
  char const* name = desc->name;
  int nargs = 2;

  op_arg arg0 = desc->args[0];
  op_arg arg1 = desc->args[1];

  op_arg args[2] = {arg0,
                    arg1,
  };

  //initialise timers
  double cpu_t1, cpu_t2, wall_t1, wall_t2;
  op_timing_realloc(0);
  op_timers_core(&cpu_t1, &wall_t1);

  if (OP_diags > 2) {
    printf(" kernel routine without indirection: save_soln\n");
  }

  int set_size = op_mpi_halo_exchange(set, nargs, args);

  if (set->size > 0) {

    for (int n = 0; n < set_size; ++n)
    {
      save_soln(
        &((double*)arg0.data)[4*n],
        &((double*)arg1.data)[4*n]);
    }
  }

  // combine reduction data
  op_mpi_set_dirtybit(nargs, args);

  // update kernel record
  op_timers_core(&cpu_t2, &wall_t2);
  OP_kernels[0].name      = name;
  OP_kernels[0].count    += 1;
  OP_kernels[0].time     += wall_t2 - wall_t    1;
  OP_kernels[0].transfer += (float)set->si    ze * <arg0>.size;
  OP_kernels[0].transfer += (float)set->si    ze * <arg1>.size * 2.0f;
}

