# OP2Summary.cmake - end-of-configure summary, consolidating the "OP2: ..."
# STATUS lines emitted earlier in one skimmable block. VERBOSE log level adds
# per-app detail.

function(_op2_summary_feature label value)
    string(LENGTH "${label}" _len)
    math(EXPR _pad "16 - ${_len}")
    if(_pad LESS 1)
        set(_pad 1)
    endif()
    string(REPEAT " " ${_pad} _spaces)
    message(STATUS "  ${label}${_spaces}${value}")
endfunction()

function(_op2_summary_yesno label enabled_var extra)
    if(${enabled_var})
        _op2_summary_feature("${label}" "${extra}")
    else()
        _op2_summary_feature("${label}" "(not enabled)")
    endif()
endfunction()

# Compose values.
if(CMAKE_BUILD_TYPE)
    set(_summary_build_type "${CMAKE_BUILD_TYPE}")
else()
    set(_summary_build_type "(not set - defaults to unoptimised)")
endif()

set(_summary_cxx "${CMAKE_CXX_COMPILER} (${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION})")
set(_summary_c   "${CMAKE_C_COMPILER} (${CMAKE_C_COMPILER_ID} ${CMAKE_C_COMPILER_VERSION})")
if(CMAKE_Fortran_COMPILER)
    set(_summary_fortran "${CMAKE_Fortran_COMPILER} (${CMAKE_Fortran_COMPILER_ID} ${CMAKE_Fortran_COMPILER_VERSION})")
else()
    set(_summary_fortran "(disabled)")
endif()

if(CMAKE_CUDA_COMPILER)
    set(_summary_cuda "${CMAKE_CUDA_COMPILER_ID} ${CMAKE_CUDA_COMPILER_VERSION} → ${CMAKE_CUDA_ARCHITECTURES}")
else()
    set(_summary_cuda "(no compiler found)")
endif()
if(CMAKE_HIP_COMPILER)
    set(_summary_hip "${CMAKE_HIP_COMPILER_ID} ${CMAKE_HIP_COMPILER_VERSION}")
else()
    set(_summary_hip "(no compiler found)")
endif()

if(MPI_FOUND)
    set(_summary_mpi_ver "${MPI_VERSION}")
    if(NOT _summary_mpi_ver)
        set(_summary_mpi_ver "${MPI_C_VERSION}")
    endif()
    if(NOT _summary_mpi_ver)
        set(_summary_mpi_ver "unknown")
    endif()

    set(_summary_mpi_lib "unknown")
    if(MPI_C_LIBRARIES)
        list(GET MPI_C_LIBRARIES 0 _summary_mpi_lib)
    endif()

    set(_summary_mpi_impl "")
    if(MPI_C_LIBRARY_VERSION_STRING)
        string(REGEX MATCH "^[^\n]+" _summary_mpi_impl "${MPI_C_LIBRARY_VERSION_STRING}")
    endif()

    # The implementation string (e.g. Open MPI's) can be long, so this is
    # printed as two summary lines rather than crammed onto one.
    if(_summary_mpi_impl)
        set(_summary_mpi_line1 "${_summary_mpi_impl}")
    else()
        set(_summary_mpi_line1 "(implementation unknown)")
    endif()

    set(_summary_mpi_line2 "MPI ${_summary_mpi_ver} standard - ${_summary_mpi_lib}")
else()
    set(_summary_mpi_line1 "(not found)")
    set(_summary_mpi_line2 "")
endif()

# Per language, so that having it for only one of them is expressible.
set(_summary_openmp "")
if(OpenMP_CXX_FOUND)
    list(APPEND _summary_openmp "C++ v${OpenMP_CXX_VERSION}")
endif()
if(OpenMP_Fortran_FOUND)
    list(APPEND _summary_openmp "Fortran v${OpenMP_Fortran_VERSION}")
endif()
if(_summary_openmp)
    string(REPLACE ";" ", " _summary_openmp "${_summary_openmp}")
else()
    set(_summary_openmp "(not found)")
endif()

if(HDF5_FOUND)
    if(OP2_HDF5_IS_PARALLEL)
        set(_summary_hdf5 "v${HDF5_VERSION} parallel - target ${_op2_hdf5_target}")
    else()
        set(_summary_hdf5 "v${HDF5_VERSION} serial - target ${_op2_hdf5_target}")
    endif()
else()
    set(_summary_hdf5 "(not found - set HDF5_ROOT)")
endif()

set(_summary_partitioners "")
if(PTScotch_FOUND)
    list(APPEND _summary_partitioners "PT-Scotch")
endif()
if(ParMETIS_FOUND)
    list(APPEND _summary_partitioners "ParMETIS")
endif()
if(KaHIP_FOUND)
    list(APPEND _summary_partitioners "KaHIP")
endif()
if(_summary_partitioners)
    string(REPLACE ";" ", " _summary_partitioners "${_summary_partitioners}")
else()
    set(_summary_partitioners "(none found)")
endif()

if(NOT OP2_ENABLE_TRANSLATOR)
    set(_summary_python "(not probed - translator disabled)")
elseif(Python3_Interpreter_FOUND)
    set(_summary_python "${Python3_EXECUTABLE} (v${Python3_VERSION})")
else()
    set(_summary_python "(not found)")
endif()

if(NOT OP2_ENABLE_TRANSLATOR)
    set(_summary_translator "(disabled - set -DOP2_ENABLE_TRANSLATOR=ON)")
elseif(OP2_HAS_TRANSLATOR)
    set(_summary_translator "found (${Python3_EXECUTABLE})")
else()
    set(_summary_translator "(install only, cannot run - missing packages, see above)")
endif()

get_property(_summary_libs_c   GLOBAL PROPERTY OP2_LIBS_C)
get_property(_summary_libs_for GLOBAL PROPERTY OP2_LIBS_FOR)
if(_summary_libs_c)
    string(REPLACE ";" ", " _summary_libs_c "${_summary_libs_c}")
else()
    set(_summary_libs_c "(none)")
endif()
if(_summary_libs_for)
    string(REPLACE ";" ", " _summary_libs_for "${_summary_libs_for}")
else()
    set(_summary_libs_for "(none)")
endif()

if(OP2_ENABLE_APPS)
    get_property(_summary_app_names   GLOBAL PROPERTY OP2_SUMMARY_APPS_NAMES)
    get_property(_summary_app_variant GLOBAL PROPERTY OP2_SUMMARY_APPS_COUNT)
    list(LENGTH _summary_app_names _summary_app_count)
    if(NOT _summary_app_variant)
        set(_summary_app_variant 0)
    endif()
    set(_summary_apps "${_summary_app_count} apps, ${_summary_app_variant} buildable variants")
else()
    set(_summary_apps "(disabled - set -DOP2_ENABLE_APPS=ON)")
endif()

# OP2_SUMMARY_TESTS_COUNT uses the same _op2_summary_track() bucket mechanism
# as OP2_SUMMARY_APPS_COUNT (OP2AppSupport.cmake); the directory count has no
# APPS-side equivalent, so it's tracked separately (OP2_SUMMARY_TESTS_DIRS,
# in OP2FunctionalTestSupport.cmake).
if(OP2_ENABLE_TESTS)
    get_property(_summary_test_dir_names GLOBAL PROPERTY OP2_SUMMARY_TESTS_DIRS)
    get_property(_summary_test_count     GLOBAL PROPERTY OP2_SUMMARY_TESTS_COUNT)
    list(LENGTH _summary_test_dir_names _summary_test_dirs)
    if(NOT _summary_test_count)
        set(_summary_test_count 0)
    endif()
    set(_summary_tests "${_summary_test_dirs} directories, ${_summary_test_count} registered tests")
else()
    set(_summary_tests "(disabled - set -DOP2_ENABLE_TESTS=ON)")
endif()

message(STATUS "")
message(STATUS "=============== OP2 configuration ===============")
_op2_summary_feature("Version:"        "${PROJECT_VERSION}")
_op2_summary_feature("Install prefix:" "${CMAKE_INSTALL_PREFIX}")
_op2_summary_feature("Build type:"     "${_summary_build_type}")
if(BUILD_SHARED_LIBS)
    _op2_summary_feature("Library type:"   "shared")
else()
    _op2_summary_feature("Library type:"   "static")
endif()
message(STATUS "")
_op2_summary_feature("C compiler:"     "${_summary_c}")
_op2_summary_feature("C++ compiler:"   "${_summary_cxx}")
_op2_summary_feature("Fortran:"        "${_summary_fortran}")
_op2_summary_feature("CUDA:"           "${_summary_cuda}")
_op2_summary_feature("HIP:"            "${_summary_hip}")
message(STATUS "")
_op2_summary_feature("MPI:"            "${_summary_mpi_line1}")
if(_summary_mpi_line2)
    _op2_summary_feature("" "${_summary_mpi_line2}")
endif()
_op2_summary_feature("OpenMP:"         "${_summary_openmp}")
_op2_summary_feature("HDF5:"           "${_summary_hdf5}")
_op2_summary_feature("Partitioners:"   "${_summary_partitioners}")
_op2_summary_feature("Python:"         "${_summary_python}")
_op2_summary_feature("Translator:"     "${_summary_translator}")
message(STATUS "")
_op2_summary_feature("C/C++ libs:"     "${_summary_libs_c}")
_op2_summary_feature("Fortran libs:"   "${_summary_libs_for}")
_op2_summary_feature("Apps:"           "${_summary_apps}")
_op2_summary_feature("Tests:"          "${_summary_tests}")
message(STATUS "==================================================")
message(STATUS "")
