# OP2Translator.cmake - locate the OP2 translator and install its payload.
#
# Sets OP2_HAS_TRANSLATOR/OP2_TRANSLATOR_COMMAND via OP2TranslatorProbe.cmake
# (shared with the installed OP2Config.cmake). Python is found, not
# provisioned: no venv, pip never invoked.

# CACHE INTERNAL, matching the probe: a plain set() would shadow the cache
# entries the probe writes and hide a successful result. Also clears a stale
# TRUE when OP2_ENABLE_TRANSLATOR is off, since return() below skips the probe.
set(OP2_HAS_TRANSLATOR FALSE CACHE INTERNAL "")
set(OP2_TRANSLATOR_COMMAND "" CACHE INTERNAL "")

if(NOT OP2_ENABLE_TRANSLATOR)
    message(STATUS "OP2: translator   = disabled (OP2_ENABLE_TRANSLATOR=OFF)")
    return()
endif()

set(_op2_translator_pkg  "${CMAKE_CURRENT_SOURCE_DIR}/translator-v2/op2-translator")
set(_op2_translator_reqs "${CMAKE_CURRENT_SOURCE_DIR}/translator-v2/requirements.txt")
set(_op2_translator_fpp  "${CMAKE_CURRENT_SOURCE_DIR}/translator-v2/fpp")

set(_op2_translator_pkg_dir "${_op2_translator_pkg}")
set(_op2_translator_reqs_file "${_op2_translator_reqs}")
include("${CMAKE_CURRENT_LIST_DIR}/OP2TranslatorProbe.cmake")

# ---------------------------------------------------------------------------
# Install rules - not gated on OP2_HAS_TRANSLATOR: the payload is static
# files, and the installed OP2Config.cmake reprobes against the consumer's
# own Python.
# ---------------------------------------------------------------------------
if(NOT OP2_ENABLE_INSTALL)
    return()
endif()

# Self-locating `<bindir>/op2-translator`, running whatever python3 is on
# PATH. The hop to the package is computed, not literal, so it survives any
# CMAKE_INSTALL_* layout or install prefix.
file(RELATIVE_PATH _op2_launcher_to_pkg
    "${CMAKE_INSTALL_FULL_BINDIR}"
    "${CMAKE_INSTALL_FULL_LIBEXECDIR}/op2/translator/pkg")

file(WRITE "${PROJECT_BINARY_DIR}/op2-translator-launcher"
"#!/bin/sh
# Auto-generated by OP2 CMake.  Locates the translator package relative to
# itself and runs it with python3 from PATH.
DIR=$(cd -- \"$(dirname -- \"$0\")\" && pwd)
exec python3 \"$DIR/${_op2_launcher_to_pkg}\" \"$@\"
")

# Translator source (invoked as `python3 <pkg-dir>`).
install(DIRECTORY
        "${_op2_translator_pkg}/"
    DESTINATION
        "${CMAKE_INSTALL_LIBEXECDIR}/op2/translator/pkg"
    PATTERN "__pycache__" EXCLUDE)

# The fpp/ subdirectory shape matters: fortran/__init__.py looks for
# `../../fpp/fpp` relative to itself.  install(PROGRAMS), not
# install(DIRECTORY), because the latter would drop fpp's execute bit.
install(PROGRAMS
        "${_op2_translator_fpp}/fpp"
    DESTINATION
        "${CMAKE_INSTALL_LIBEXECDIR}/op2/translator/fpp")
install(FILES
        "${_op2_translator_fpp}/LICENSE.txt"
    DESTINATION
        "${CMAKE_INSTALL_LIBEXECDIR}/op2/translator/fpp")

# Bake the version so getVersion() in the installed pkg doesn't `git describe`.
file(WRITE "${PROJECT_BINARY_DIR}/op2-translator-VERSION"
    "${PROJECT_VERSION}\n")
install(FILES
        "${PROJECT_BINARY_DIR}/op2-translator-VERSION"
    DESTINATION
        "${CMAKE_INSTALL_LIBEXECDIR}/op2/translator/pkg"
    RENAME VERSION)

# Jinja templates - `jinja.py` looks them up via `../resources/templates`
# relative to itself, so this must land under libexec/op2/translator/
# (one level up from pkg/).
install(DIRECTORY
        "${CMAKE_CURRENT_SOURCE_DIR}/translator-v2/resources"
    DESTINATION
        "${CMAKE_INSTALL_LIBEXECDIR}/op2/translator")

# Ship requirements.txt too so downstream users know what to `pip install`.
install(FILES
        "${_op2_translator_reqs}"
    DESTINATION
        "${CMAKE_INSTALL_LIBEXECDIR}/op2/translator")

# Self-locating launcher on $PATH.
install(PROGRAMS
        "${PROJECT_BINARY_DIR}/op2-translator-launcher"
    DESTINATION "${CMAKE_INSTALL_BINDIR}"
    RENAME op2-translator)
