//
// auto-generated by op2.py
//

//user function
#include "../dotR.h"

// host stub function
void op_par_loop_dotR(char const *name, op_set set,
  op_arg arg0,
  op_arg arg1){

  int nargs = 2;
  op_arg args[2];

  args[0] = arg0;
  args[1] = arg1;

  // initialise timers
  double cpu_t1, cpu_t2, wall_t1, wall_t2;
  op_timing_realloc(6);
  op_timers_core(&cpu_t1, &wall_t1);


  if (OP_diags>2) {
    printf(" kernel routine w/o indirection:  dotR");
  }

  int set_size = op_mpi_halo_exchanges(set, nargs, args);

  
  int reduct_bytes = 0;
  reduct_bytes = ROUND_UP(arg1.dim*sizeof(double)*set_size);  
  reallocReductArrays(reduct_bytes);
  
  reduct_bytes=0;
  double* red1 = (double*)(OP_reduct_h+reduct_bytes);
  reduct_bytes+=arg1.dim*sizeof(double)*set_size;
  
  for (int i=0; i<arg1.dim*set_size; i++){
      red1[i]=0;
  }
  
  
  if (set->size >0) {

    for ( int n=0; n<set_size; n++ ){
      dotR(
        &((double*)arg0.data)[1*n],
        //(double*)arg1.data);
        &red1[1*n]);
    }
  }
  
  reprLocalSum(&arg1,set_size,red1);
  
  // combine reduction data
  op_mpi_repr_inc_reduce_double(&arg1,(double*)arg1.data);
  op_mpi_set_dirtybit(nargs, args);

  // update kernel record
  op_timers_core(&cpu_t2, &wall_t2);
  OP_kernels[6].name      = name;
  OP_kernels[6].count    += 1;
  OP_kernels[6].time     += wall_t2 - wall_t1;
  OP_kernels[6].transfer += (float)set->size * arg0.size;
}
